version: '3'

networks:
  net:
    driver: bridge

services:
  db:
    image: mysql:latest
    networks:
      - net
    env_file:
      - .env
    command: ['mysqld', '--character-set-server=${DNMP_MYSQL_CHARSET}', '--collation-server=${DNMP_MYSQL_CHARSET_COLLATE}', '--port=${DNMP_MYSQL_PORT}']
    volumes:
      - ./Docker/mysql/script:/root/script
      - ./Docker/mysql/dump:/root/dump:ro
      - ./Docker/mysql/config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
    ports:
      - "${DNMP_MYSQL_PORT}:${DNMP_MYSQL_PORT}"
  nginx:
    build: ./Docker/nginx/
    networks:
      - net
    env_file:
      - .env
    volumes:
      - ./Docker/nginx/config/site.conf:/etc/nginx/template/site.conf:ro
      - ./Docker/nginx/config/general.conf:/etc/nginx/conf.d/general.conf:ro
      - ./Docker/nginx/log:/var/log/nginx/${DNMP_NGINX_DOMAIN}
      - ./application/html:/usr/share/nginx/${DNMP_NGINX_DOMAIN}/www
      - ./Docker/nginx/script:/root/script
      - ./Docker/static/app/dist:/usr/share/nginx/static.${DNMP_NGINX_DOMAIN}/dist
    depends_on:
      - php
    ports:
      - "${DNMP_NGINX_PORT}:${DNMP_NGINX_PORT}/tcp"
    command: /bin/bash -c "/root/script/template_nginx.sh /etc/nginx/template/site.conf > /etc/nginx/conf.d/default.conf && exec nginx-debug -g 'daemon off;'"
  php:
    &base-php-fpm
      build: ./Docker/php-fpm/
      networks:
        - net
      env_file:
        - .env
      depends_on:
        - db
      volumes:
        - ./Docker/php-fpm/config/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
        - ./Docker/php-fpm/config/php.ini:/usr/local/etc/php/php.ini:ro
        - ./application:/var/www
        - ./Docker/php-fpm/log:/var/log
#        - ./.env:/var/www/.env:rw
      expose:
        - ${DNMP_PHP_PORT}
#  phpfpm2:
#    <<: *base-php-fpm
  redis:
    image: redis:5-alpine
    networks:
      - net
    env_file:
      - .env
    volumes:
      - ./Docker/redis/config/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      ['redis-server', '/usr/local/etc/redis/redis.conf', '--port', '${REDIS_PORT}', '--requirepass', '${REDIS_PASSWORD}']
    expose:
      - ${REDIS_PORT}
  static:
    build: ./Docker/static/
    networks:
      - net
    env_file:
      - .env
    volumes:
      - ./Docker/static/app:/home/node/app
      - ./Docker/static/log:/root/.npm/_logs
